Repository auxmoney/OpentracingBundle-core, pull requests merged in 2020-03, with the labels that each got.

#20 fix!: sort spans in functional tests by startTime
  .github/workflows/release.yml
  .travis.yml
  README.md
  Tests/Functional/JaegerFunctionalTest.php
Labels: bug

#22 Added esi support doc
  README.md
  doc/README.md
  doc/esi.md
  doc/img/esi-trace.png
Labels: documentation

#24 WIP: feat!: add sampler configuration
  Factory/TracerFactory.php
  Internal/CachedOpentracing.php
  Resources/config/services.yaml
  Tests/Internal/CachedOpentracingTest.php
Labels: enhancement

#27 doc: reflect jaeger library upgrade and minor cleanup
  README.md
Labels: documentation

#28 feat: semantic release
  .github/workflows/release.yml
  .gitignore
  .releaserc.json
  .versionrc.json
  CHANGELOG.md
  README.md
Labels: enhancement

#29 fix: update documentation
  MAINTAINING.md
  README.md
Labels: documentation

#33 Could not finish active span, missing active scope (part 2)
  EventListener/FinishControllerSpanSubscriber.php
  EventListener/StartControllerSpanSubscriber.php
  Tests/EventListener/FinishControllerSpanSubscriberTest.php
Labels: bug
