Repository auxmoney/OpentracingBundle-core, pull requests merged in 2020-06, with the labels that each got.

#39 fix: add trace id header
  AbstractOpentracingBundle.php
  EventListener/FinishControllerSpanSubscriber.php
  README.md
  Resources/config/services.yaml
  Tests/EventListener/FinishControllerSpanSubscriberTest.php
  Tests/Functional/Scripts/requireAdditionalVendors.sh
  Tests/Functional/TestProjectFiles/default/config/packages/psr18.yaml
  Tests/Mock/EventWithResponse.php
Labels: enhancement

#40 feat: add span origin tag
  .travis.yml
  EventListener/StartCommandSpanSubscriber.php
  EventListener/StartControllerSpanSubscriber.php
  EventListener/StartRootSpanSubscriber.php
  Internal/Constant.php
  Internal/Decorator/PSR18ClientDecorator.php
  Tests/EventListener/StartCommandSpanSubscriberTest.php
  Tests/EventListener/StartControllerSpanSubscriberTest.php
  Tests/EventListener/StartRootSpanSubscriberTest.php
  Tests/Functional/FunctionalSF3Test.allFeatures.expected.yaml
  Tests/Functional/FunctionalSF3Test.cmdException.expected.yaml
  Tests/Functional/FunctionalSF3Test.php
  Tests/Functional/FunctionalSF3Test.webException.expected.yaml
  Tests/Functional/FunctionalTest.allFeatures.expected.yaml
  Tests/Functional/FunctionalTest.cmdException.expected.yaml
  Tests/Functional/FunctionalTest.php
  Tests/Functional/FunctionalTest.webException.expected.yaml
  Tests/Functional/JaegerFunctionalTest.php
  Tests/Functional/JaegerWebFunctionalTest.php
  Tests/Functional/Scripts/requireAdditionalVendors.sh
  Tests/Internal/Decorator/PSR18ClientDecoratorTest.php
Labels: enhancement

#41 chore: add rabbitmq plugin to documentation
  README.md
Labels: documentation

#42 Typo in readme
  README.md
Labels: documentation

#43 chore: add new emagtech rabbitmq plugin
  README.md
Labels: documentation

#44 Route tag can be omitted with controller functions
  EventListener/StartControllerSpanSubscriber.php
  Tests/EventListener/StartControllerSpanSubscriberTest.php
Labels: bug
